kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: django-hpa
  namespace: django-ns

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: django-ns

  minReplicas: 1
  maxReplicas: 5


  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization : 2
